### ISSUE TITLE
URBMediaFocusViewController fails to link against iOS 6.1

### ISSUE THREAD

**Issue by cbowns** [u10int/URBMediaFocusViewController#25]
Despite the readme claiming "NOTE: This project has been updated to work with and tested against iOS 6. However, the UIDynamics features are only support in iOS 7+.", the included sample project fails to build when its deployment target is changed to 6.0 and is built for iOS 6.1:

```
dyld: Symbol not found: _OBJC_CLASS_$_UIAttachmentBehavior
  Referenced from: /Users/cbowns/Library/Application Support/iPhone Simulator/6.1/Applications/E647C36C-6255-4E4B-A976-D193A0EE7870/URBMediaFocusViewControllerDemo.app/URBMediaFocusViewControllerDemo
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 in /Users/cbowns/Library/Application Support/iPhone Simulator/6.1/Applications/E647C36C-6255-4E4B-A976-D193A0EE7870/URBMediaFocusViewControllerDemo.app/URBMediaFocusViewControllerDemo
```

URBMediaFocusViewController has several properties which are only available on 7.0 and later:

```
@property (nonatomic, strong) UIDynamicAnimator *animator;
@property (nonatomic, strong) UISnapBehavior *snapBehavior;
@property (nonatomic, strong) UIPushBehavior *pushBehavior;
@property (nonatomic, strong) UIAttachmentBehavior *panAttachmentBehavior;
@property (nonatomic, strong) UIDynamicItemBehavior *itemBehavior;
```

There's ways to make this class work against pre-7.0, but it requires some hoop-jumping. Is the intention to make this build and run on 6.x? If so, I can help fix it up, but if not, the readme should be updated.

**Comment by u10int** [comment]
Closing this out since minimum requirement since the class is no longer guaranteed to support iOS older than 8.0.
