### ISSUE TITLE
iOS 8 6 and 6 plus, scales presenting view forward briefly before scaling back to present image

### ISSUE THREAD

**Issue by Shagans982** [u10int/URBMediaFocusViewController#36]
I discovered a small bug that appears to only occur in the 6 & 6 plus models. The presenting view seems to scale forward quickly before scaling back and presenting the image. I wasn't sure if this had anything to do with the zoom mode now available on both models but it doesn't seem to matter, it still occurs in both modes.

**Comment by u10int** [comment]
@Shagans982 Looks like using `renderInContext` instead of iOS 7's `drawViewHierarchyInRect:afterScreenUpdates:` fixed this issue, which I noticed when working on this other issue: https://github.com/u10int/URBMediaFocusViewController/issues/39
