### ISSUE TITLE
Background not getting blurred from time to time

### ISSUE THREAD

**Issue by pawelkata** [u10int/URBMediaFocusViewController#39]
Hello,

I've encountered a very strange issue: from time to time, most often during first usage, the background is not blurred properly. I tried in both the simulator and on the device (iPhone 5 and iPhone 6, latest iOS).

![ios simulator screen shot 11 gru 2014 12 59 25](https://cloud.githubusercontent.com/assets/962904/5393860/61f95c96-8136-11e4-8f1a-d894a898c3c9.png)

Here's my implementation:
```
NSString *key = [[SDWebImageManager sharedManager] cacheKeyForURL:imgUrl];
UIImage *image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:key];
_mfvc = [[URBMediaFocusViewController alloc] init];
_mfvc.shouldDismissOnTap = YES;
_mfvc.parallaxEnabled = YES;
_mfvc.shouldBlurBackground = YES;
[_mfvc showImage:image fromView:weakSelf.navigationController.parentViewController.view];
```

(I call it like that because I'm using a TabBar UI, with view controllers embedded in NavigationControllers in each tab.)

It doesn't seem to matter if I call showImage:fromView on the main thread or not (I tried it both ways and the problem occured both times).

Is there any solution to this issue?

**Comment by u10int** [comment]
@pawelkata I just pushed an update that should fix this for you (it works better now in my testing). There are some issues with iOS 7's `drawViewHierarchyInRect:afterScreenUpdates:` in iOS 8 that was likely causing some issues, so I modified the code that generates the screenshot to just use `renderInContext:` instead. Let me know if you still notice any issues.

**Comment by pawelkata** [comment]
I just tested it. It's working great! Thank you! :D
