### ISSUE TITLE
When one instance of URBMediaFocusViewController has been deallocated,it should dismiss itself automatically?

### ISSUE THREAD

**Issue by mingweizhang** [u10int/URBMediaFocusViewController#40]
well, If we use URBMediaFocusViewController as a VC's property,it works correctly.But I met a problem in some cases. For example,if I coded like this(it's similar to my case that the instance dealloc after I "showImage: fromView:" ).
```
- (void)showImage
{
    URBMediaFocusViewController *urbVC = [[URBMediaFocusViewController alloc] init];
    urbVC.shouldDismissOnTap = YES;
    urbVC.shouldRotateToDeviceOrientation = NO;
    [urbVC showImage:self.imageView.image fromView:self.imageView];
}
```
we know,"urbVC" will dealloc after "}".But it still presented the image.So when I tap the image,it will crash with the log"message sent to deallocated instance ".

**Comment by mingweizhang** [comment]
PS:in my case,I make the method "- (void)dismiss:(BOOL)animated;" public.When my VC that has a property of URBMediaFocusViewController instance dealloc,I sent a message "dismiss" to VC's URBMediaFocusViewController instance.
But it isn't a good way.anyone has another way?

**Comment by u10int** [comment]
You should be storing your URBMediaFocusViewController instance on a private property in your view controller which will prevent it from being deallocated as well as only requiring a single instance to be allocated:

```
- (void)showImage
{
    if (!self.mediaFocusController) {
        URBMediaFocusViewController *urbVC = [[URBMediaFocusViewController alloc] init];
        urbVC.shouldDismissOnTap = YES;
        urbVC.shouldRotateToDeviceOrientation = NO;
    }
    [self.mediaFocusController showImage:self.imageView.image fromView:self.imageView];
}
```

**Comment by mingweizhang** [comment]
yeah,URBMediaFocusViewController instance was the private property in my view controller.But,my view controller dealloc after "[self.mediaFocusController showImage:self.imageView.image fromView:self.imageView];",and the URBMediaFocusViewController instance also dealloc.
Now,I create a singleton instance to store my URBMediaFocusViewController instance instead of a property in my view controller.
thank you for your reply all the same.
