### ISSUE TITLE
Tap on image crashes on Xcode 6 and swift

### ISSUE THREAD

**Issue by jerometonnelier** [u10int/URBMediaFocusViewController#42]
Though the component works like a charm with iOS7 and objectiveC, using the controller in a swift project result in a severe crash on the image tap. I could not even trap the crash with breakpoints in the handleDismissFromTap: :-/

#update#: As it seems, all gestures crash the app :(

**Comment by u10int** [comment]
Can you provide more details of your use case or the Swift code you are using? I just tested a demo project where I converted the code in DemoViewController.m to Swift and everything worked fine without any crashes.

**Comment by BCGray00** [comment]
Any update as I have the same problem

**Comment by u10int** [comment]
@BCGray00 I asked @jerometonnelier for more details and/or code regarding the crash he's seeing as I can't duplicate the issue. Can you provide any details about the crash?

**Comment by jerometonnelier** [comment]
Oups sorry I totally forgot about that :( In the meantime, I used another component, so I won't be able to provide any code ou crash log :( Sorry about that.

**Comment by BCGray00** [comment]
same, i changed aswell
