### ISSUE TITLE
Swipe dismisses image while zooming

### ISSUE THREAD

**Issue by mamouneyya** [u10int/URBMediaFocusViewController#45]
After zooming the image, any swipe is handled as 'swipe to dismiss', while it should actually considered as pan movement.

**Comment by u10int** [comment]
@mamouneyya Can you provide more details as to what you're referring to here? Are you saying that swiping on an image that's been zoomed is actually dismissing the image from the zoomed state?

**Comment by mamouneyya** [comment]
Yes.

**Comment by u10int** [comment]
Still haven't been able to reproduce this issue, but made some tweaks in 0.9.0 that should prevent the pan gesture from being enabled when zoomed into an image, which is causing this issue.
