### ISSUE TITLE
Strange behavior when pan while zooming

### ISSUE THREAD

**Issue by mamouneyya** [u10int/URBMediaFocusViewController#46]
While zooming, sometimes a slow pan moves the image inside the view, which affects its initial location in the second opening. Please take a look at the this video, which clearly shows the issue: http://youtu.be/8xdTcuGrqhI

**Comment by u10int** [comment]
@mamouneyya I can't seem to duplicate this issue yet. Are you seeing this issue every time or just occasionally, and does it happen on the very first time you focus an image or after a certain number of views? Also, is this happening on a specific version of iOS or any > 7.0?

**Comment by mamouneyya** [comment]
To be honest I didn't try it on a real device yet. I was searching for good solution and used the simulator (with iOS 8, by the way) to test the plugin. (This is applicable also to issue #45 if that would help.)

**Comment by u10int** [comment]
@mamouneyya I just pushed up some changes that should fix this issue as I was able to reproduce what you were seeing before the changes, but not after. Can you test and verify you are no longer seeing this problem?

**Comment by daxrahusen** [comment]
I still have the the problem @u10int

**Comment by u10int** [comment]
@daxrahusen Which version of iOS are you seeing this issue on both the simulator and device?

**Comment by daxrahusen** [comment]
@u10int I'm using 8.2 and Xcode 6.2, on both the simulator and iDevice

**Comment by u10int** [comment]
Still haven't been able to reproduce this issue, but made some tweaks in 0.9.0 that should prevent the pan gesture from being enabled when zoomed into an image, which is causing this issue.
