### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by lengqingfeng** [u10int/URBMediaFocusViewController#48]
CTNativeGlyphStorage gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:]: unrecognized selector sent to instance 0x13e269b70

**Comment by u10int** [comment]
@lengqingfeng Can you provide more details? Based on what you posted your crash is coming from the class `CTNativeGlyphStorage`.

**Comment by lengqingfeng** [comment]
i know this question ！thank you becomes network not finish tuch image 发自网易邮箱大师
            在2015年09月19日 07:34，Nicholas Shipes 写道:@lengqingfeng Can you provide more details? Based on what you posted your crash is coming from the class CTNativeGlyphStorage.

**Comment by u10int** [comment]
Closing this out since based on the error provided the crash is originating on CTNativeGlyphStorage and not this class and no additional implementation details were provided.
