### ISSUE TITLE
App crashing on the showImage in IOS 9

### ISSUE THREAD

**Issue by vickyrappier** [u10int/URBMediaFocusViewController#49]
Hello Developer,

I am using this component to show the image Preview. In IOS 9 the application is crashing in this code.

 //View photo
    URBMediaFocusViewController *mediaFocusController; mediaFocusController = [[URBMediaFocusViewController alloc] init];
    [mediaFocusController showImage:profileImageBtn.imageView.image fromView:self.view];

Also note that This is called in UIAlertcontroller action block.  And also tried to put this in main thread from the block called by performselector in main thread.

Can anyone help over this.

**Comment by u10int** [comment]
@vickyrappier If you're calling this within an UIAlertController action block, then it's likely getting released when the block finishes running before interacting with the view. You'll likely want to retain your URBMediaFocusController instance on a private property until you no longer need it to prevent this. 

Also, if you can provide a stack trace of the crash that would help narrow it down as well.
